<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Profilweb_config_model extends CI_Model
{

    public $table = 'profilweb_config';
    public $id = 'id_config';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    //get field

    function get_field(){
      $table=$this->table;
      $sql=$this->db->query("SELECT * FROM `$table`"); //ganti * untuk custom field yang ditampilkan pada table
      return $sql->list_fields();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_config', $q);
	$this->db->or_like('service_tagline', $q);
	$this->db->or_like('service_judul', $q);
	$this->db->or_like('service_deskripsi', $q);
	$this->db->or_like('whychoose_tagline', $q);
	$this->db->or_like('whychoose_judul', $q);
	$this->db->or_like('whychoose_deskripsi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_config', $q);
	$this->db->or_like('service_tagline', $q);
	$this->db->or_like('service_judul', $q);
	$this->db->or_like('service_deskripsi', $q);
	$this->db->or_like('whychoose_tagline', $q);
	$this->db->or_like('whychoose_judul', $q);
	$this->db->or_like('whychoose_deskripsi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Profilweb_config_model.php */
/* Location: ./application/models/Profilweb_config_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-30 04:42:53 */
/* http://harviacode.com */